package com.lyr.secKill.dao;

import com.lyr.secKill.dataobject.UserDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Oct 09 17:47:48 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Oct 09 17:47:48 CST 2019
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Oct 09 17:47:48 CST 2019
     */
    UserDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Oct 09 17:47:48 CST 2019
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Oct 09 17:47:48 CST 2019
     */
    int updateByPrimaryKey(UserDO record);

    int insertUser(@Param("name") String name, @Param("telephone") String i);

    UserDO selectByTelephone(String telephone);
}